// movies Data
export const movies = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    year: "1994",
    runtime: "142",
    genres: ["Crime", "Drama"],
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    plot: "Two imprisoned",
    posterUrl:
      "https://m.media-amazon.com/images/M/MV5BMTI4MDk4NjYxNF5BMl5BanBnXkFtZTcwMjQ5NjM3Mw@@._V1_SX300.jpg",
    imdbRating: "9.3",
    imdbVotes: "2,341,835",
    imdbId: "tt0111161",
    type: "movie",
    boxOffice: "$28.34M",
    production: "Castle Rock Entertainment",
  },
  {
    id: 2,
    title: "The Godfather",
    year: "1972",
    runtime: "175",
    genres: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    actors: "Marlon Brando, Al Pacino, James Caan, Diane Keaton",
    plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    posterUrl:
      "https://m.media-amazon.com/images/M/MV5BMTI4MDk4NjYxNF5BMl5BanBnXkFtZTcwMjQ5NjM3Mw@@._V1_SX300.jpg",
    imdbRating: "9.2",
    imdbVotes: "1,609,560",
    imdbId: "tt0068646",
    type: "movie",
    boxOffice: "$134.97M",
    production: "Paramount Pictures",
  },
  {
    id: 3,
    title: "The Godfather: Part II",
    year: "1974",
    runtime: "202",
    genres: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    actors: "Al Pacino, Robert De Niro, Robert Duvall, Diane Keaton",
    plot: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
    posterUrl:
      "https://m.media-amazon.com/images/M/MV5BMTI4MDk4NjYxNF5BMl5BanBnXkFtZTcwMjQ5NjM3Mw@@._V1_SX300.jpg",
    imdbRating: "9.0",
    imdbVotes: "1,146,972",
    imdbId: "tt0071562",
    type: "movie",
    boxOffice: "$57.30M",
    production: "Paramount Pictures",
  },
  {
    id: 4,
    title: "The Dark Knight",
    year: "2008",
    runtime: "152",
    genres: ["Action", "Crime", "Drama", "Thriller"],
    director: "Christopher Nolan",
    actors: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.",
    posterUrl:
      "https://m.media-amazon.com/images/M/MV5BMTI4MDk4NjYxNF5BMl5BanBnXkFtZTcwMjQ5NjM3Mw@@._V1_SX300.jpg",
    imdbRating: "9.0",
    imdbVotes: "2,223,338",
    imdbId: "tt0468569",
    type: "movie",
    boxOffice: "$534.86M",
    production: "Warner Bros. Pictures",
  },
];
